const $ = id => document.getElementById(id);
const UI_THEME_KEY = "waveguard-ui-theme";
function applyUiTheme(theme, persist=false) {
  const normalized=theme==="dark"?"dark":"light";
  document.body.dataset.uiTheme=normalized;
  document.querySelectorAll("[data-ui-theme-choice]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.uiThemeChoice===normalized)));
  if(persist)localStorage.setItem(UI_THEME_KEY,normalized);
}
const names = [..."ABCDEFGH"];
const picoTraceColors=["#2e73e8","#e34b4b","#39ae50","#e5ce29","#a060cb","#a3a3a3","#56b5df","#d44bb7"];
function experimentAccent(){return getComputedStyle(document.body).getPropertyValue('--signal').trim()||'#2f73ff';}

const fullGuide = window.INTERFERENCE_GUIDE || [];
const specs = [
  {title:"拉线棒浮空与低阻连接",purpose:"验证低阻接棒是否稳定抑制发射串扰，并检查回波是否同时下降。",wiring:"保持 PZT 机械安装和 RX− 接地不变；只改变 PZT− 到棒的电气连接。",conditions:[["float","棒与 PZT 完全电气隔离"],["grounded","PZT− 低阻接棒（记录实测 0～2 Ω）"]],fields:[["resistance_ohm","实测连接电阻 Ω","number"]]},
  {title:"棒连接串联电阻扫描",purpose:"观察低阻高频参考作用，并估算 R₅₀。",wiring:"PZT− → Rs → 拉线棒；每个电阻保持其他接线不变。",scan:{key:"resistance_ohm",label:"电阻 Ω",values:[0,2,10,100,1000,10000,100000]}},
  {title:"棒对系统地共模电压",purpose:"用同步双通道观察棒电压与 RX 干扰的相关和 75 kHz 相位。",wiring:"棒保持浮空；高阻探头测棒对公共地，另一路测 RX。使用页面指定的探头倍率。",warning:"探头输入阻抗仍会加载浮空棒；记录实际探头和接地位置。",conditions:[["float","棒浮空，同步测棒电压和 RX"]],fields:[["probe_description","探头型号 / 接地位置","text"]]},
  {title:"距离 × 棒状态",purpose:"检查接棒后残余干扰是否随 TX–RX 距离衰减；拟合 a/rⁿ+b。",wiring:"逐点改变 TX 到 PZT 的距离；每个距离分别测棒浮空和低阻连接。",scan:{key:"distance_cm",label:"距离 cm",values:[5,10,20,40,80],states:[["float","浮空"],["grounded","接棒"]]}},
  {title:"普通线、双绞线、屏蔽双绞线",purpose:"比较不同 RX 走线拾取干扰的程度。",wiring:"PZT/TX 位置、棒状态保持不变，只替换 RX 引线；记录屏蔽层接法。",conditions:[["normal","普通线"],["twisted","紧密双绞"],["shielded_twisted","屏蔽双绞"]],fields:[["shield_connection","屏蔽层连接方式","text"]]},
  {title:"接收回路面积扫描",purpose:"检验感应干扰是否随回路面积变化。",wiring:"PZT/TX 位置和引线长度不变，调整两根 RX 线间距，并估计实际闭合回路面积。",scan:{key:"area_cm2",label:"实测/估计面积 cm²",values:[0.5,2,5,10]}},
  {title:"接收回路方向扫描",purpose:"检验磁耦合的角度依赖。",wiring:"保持 PZT 位置，只旋转 RX 引线形成的回路平面。",scan:{key:"angle_deg",label:"角度 °",values:[0,45,90,135]}},
  {title:"Dummy PZT",purpose:"用等效电容剥离真实压电机械响应。",wiring:"测量 PZT 电容，使用相近普通电容，保持接线长度、位置与棒状态。",conditions:[["real","真实 PZT"],["dummy","等效电容 Dummy"]],fields:[["capacitance_pf","实际电容 pF","number"]]},
  {title:"TX 工作、机械耦合关闭",purpose:"对比早期电气串扰与可能的晚到导波。",wiring:"先测正常状态，再移开或减弱 TX 对棒的机械耦合；尽量保持 TX 电流不变。",conditions:[["normal","正常机械耦合"],["no_mech","机械耦合关闭/显著减弱"]],fields:[["method","机械耦合改变方法","text"]]},
  {title:"现有共地与 Star/Kelvin 回流",purpose:"判断公共阻抗耦合的贡献。",wiring:"先测当前长 BNC/公共地；再让 TX 功率回流与 RX/Pico 回流分别到受控星点。",warning:"必须检查 BNC 屏蔽、USB 和电源是否仍提供并联公共回流；记录实际连接，不能仅凭“星型”名称判定隔离。",conditions:[["common","当前公共地"],["star","Star/Kelvin 回流"]],fields:[["return_path","实际回流路径和星点位置","text"]]},
  {title:"公共地连接长度扫描",purpose:"检查共享地导体长度对串扰的影响。",wiring:"只改变 TX−/RX− 公共连接长度，其他接线、走向与测量位置尽量不变。",scan:{key:"length_cm",label:"公共地长度 cm",values:[10,50,100,200]}},
  {title:"静电屏蔽",purpose:"结合双绞实验，区分电场与磁场耦合线索。",wiring:"保持 RX 导线形式，比较无屏蔽与 TX/RX 间有接地开槽导电屏蔽。",warning:"避免形成闭合金属环包围磁致伸缩区域，记录屏蔽板接地点与尺寸。",conditions:[["no_shield","无屏蔽"],["shield","开槽静电屏蔽"]],fields:[["shield_description","屏蔽板及接地说明","text"]]},
];
let session=null, summary=null, current=1, conditionIndex=0, captureId=null, captureReady=false, pendingVariables=null, latestWave=null, selectedPreview=null;
const previewCache=new Map();let comparisonSpectra=[],spectraGeneration=0;
const checklistState=new Map();
let config=null;
const n=id=>Number($(id).value);
const message=s=>{$("message").textContent=s;};
function askConfirm(text){return new Promise(resolve=>{const dialog=$("confirmation");$("confirmationText").textContent=text;const finish=value=>{dialog.close();$("confirmYes").onclick=null;$("confirmNo").onclick=null;resolve(value)};$("confirmYes").onclick=()=>finish(true);$("confirmNo").onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false)};dialog.showModal()})}
async function api(path, method="GET", body) {
  const response=await fetch(path,{method,headers:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});
  const data=await response.json(); if(!response.ok)throw Error(data.error||`${response.status}`);return data;
}
function windows(){return {t0:n("t0"),baseline_start:n("baselineStart"),baseline_end:n("baselineEnd"),tail_end:n("tailEnd"),echo_start:$("echoStart").value===""?null:n("echoStart"),echo_end:$("echoEnd").value===""?null:n("echoEnd")};}
function validateWindows(){const w=windows();const cycles=session?.config.awg.cycles||n("cycles");if(w.baseline_start>=w.baseline_end||w.baseline_end>=0||w.tail_end<=0)throw Error("基线窗口须在激励前，尾振长度须大于零");if((w.echo_start===null)!==(w.echo_end===null))throw Error("回波窗口需同时填写起止");if(w.echo_start!==null&&(w.echo_start>=w.echo_end||w.echo_start<cycles/75000*1e6))throw Error("回波窗口无效或与发射窗重叠");return w;}
function settings(){try{return JSON.parse(localStorage.getItem("pico4824a-settings")||"{}")}catch{return {}}}
function fillSelect(id, values, chosen){$(id).innerHTML=values.map(v=>`<option value="${v}">${v}</option>`).join("");$(id).value=chosen;}
async function initialize(){config=await api("/api/config");const s=settings();for(const id of ["rx","rod","trigger"])fillSelect(id,names,id==="rx"?"B":id==="rod"?"C":(s.triggerSource||"A"));for(const id of ["rxRange","rodRange","triggerRange"])fillSelect(id,["10mV","20mV","50mV","100mV","200mV","500mV","1V","2V","5V","10V","20V","50V"],s.inputRange||"5V");
  const set=(id,key,f=Number)=>{if(s[key]!==undefined)$(id).value=f(s[key]);};
  set("sampleRate","sampleRate");set("duration","captureDurationUs");set("prePercent","triggerPositionPercent");set("triggerLevel","triggerLevel");set("triggerTimeout","triggerTimeout");set("cycles","awgCycles");set("vpp","awgVpp");set("offset","awgOffset");$("simulate").checked=Boolean(s.simulate);$("rx").value=s.chB===false?"A":"B";
  for(const [id,key] of [["rxRange",`ch${$("rx").value}Range`],["rodRange",`ch${$("rod").value}Range`],["triggerRange",`ch${$("trigger").value}Range`]])if(s[key])$(id).value=s[key];
  const stored=localStorage.getItem("interference-session-id");if(stored){try{const data=await api(`/api/interference/session?id=${encodeURIComponent(stored)}`);restore(data);}catch{localStorage.removeItem("interference-session-id")}}
  const deepLink=/^#exp-(\d{1,2})$/.exec(location.hash);if(deepLink)current=Math.max(1,Math.min(12,Number(deepLink[1])));
  render();}
function buildConfig(){const c=structuredClone(config);const rate=n("sampleRate")*1e6,total=Math.round(rate*n("duration")*1e-6);c.sample_rate_hz=rate;c.pre_trigger_samples=Math.round(total*n("prePercent")/100);c.post_trigger_samples=total-c.pre_trigger_samples;c.awg.enabled=true;c.awg.waveform="hann_burst";c.awg.frequency_hz=75000;c.awg.cycles=n("cycles");c.awg.pk_to_pk_v=n("vpp");c.awg.offset_v=n("offset");c.awg.buffer_samples=Number(settings().awgBufferSamples)||8192;c.awg.trigger_source="software";c.trigger.enabled=true;c.trigger.source=$("trigger").value;c.trigger.threshold_v=n("triggerLevel");c.trigger.auto_trigger_ms=n("triggerTimeout");for(const name of names){c.channels[name].enabled=[ $("rx").value,$("rod").value,$("trigger").value].includes(name);c.channels[name].range=name===$("rx").value?$("rxRange").value:name===$("rod").value?$("rodRange").value:$("triggerRange").value;}return c;}
async function createSession(){try{if($("rx").value===$("rod").value||$("rx").value===$("trigger").value||$("rod").value===$("trigger").value)throw Error("RX、棒电压和参考通道请选择不同通道");const w=validateWindows(),c=buildConfig();if(!await askConfirm(`锁定 75 kHz、${c.awg.cycles} 周期、${c.awg.pk_to_pk_v} Vpp、${n("sampleRate")} MS/s 与所选通道/量程？`))return;const reply=await api("/api/interference/session","POST",{config:c,repeats:n("repeats"),channels:{rx:$("rx").value,rod:$("rod").value,trigger:$("trigger").value,rx_probe:n("rxProbe"),rod_probe:n("rodProbe")},windows_us:w});restore({session:reply.session,summary:{rows:[],fits:{},evidence:{}}});localStorage.setItem("interference-session-id",session.id);message("会话已建立；请逐项确认接线并采集。") }catch(e){message(e.message)}}
function restore(data){session=data.session;summary=data.summary;for(const [id,value] of [["rx",session.channels.rx],["rod",session.channels.rod],["trigger",session.channels.trigger],["rxProbe",session.channels.rx_probe],["rodProbe",session.channels.rod_probe],["sampleRate",session.config.sample_rate_hz/1e6],["duration",(session.config.pre_trigger_samples+session.config.post_trigger_samples)/session.config.sample_rate_hz*1e6],["prePercent",session.config.pre_trigger_samples/(session.config.pre_trigger_samples+session.config.post_trigger_samples)*100],["triggerLevel",session.config.trigger.threshold_v],["triggerTimeout",session.config.trigger.auto_trigger_ms],["cycles",session.config.awg.cycles],["vpp",session.config.awg.pk_to_pk_v],["offset",session.config.awg.offset_v],["repeats",session.repeats],["rxRange",session.config.channels[session.channels.rx].range],["rodRange",session.config.channels[session.channels.rod].range],["triggerRange",session.config.channels[session.channels.trigger].range],["t0",session.windows_us.t0],["baselineStart",session.windows_us.baseline_start],["baselineEnd",session.windows_us.baseline_end],["tailEnd",session.windows_us.tail_end],["echoStart",session.windows_us.echo_start??""],["echoEnd",session.windows_us.echo_end??""]])$(id).value=value;
  document.querySelectorAll("#setup input,#setup select").forEach(el=>el.disabled=true);$("createSession").disabled=true;$("newSession").disabled=false;$("reanalyze").disabled=false;$("sessionId").textContent=`会话 ${session.id}`;$("setup").open=false;current=Math.max(1,Math.min(12,session.completed_experiments.length+1));render();}
async function newSession(){if(captureId!==null)return;if(!await askConfirm("开始新会话？当前会话的已存波形仍保留在本机数据目录，可通过会话编号恢复。"))return;localStorage.removeItem("interference-session-id");session=null;summary=null;current=1;conditionIndex=0;latestWave=null;selectedPreview=null;previewCache.clear();comparisonSpectra=[];document.querySelectorAll("#setup input,#setup select").forEach(el=>el.disabled=false);$("createSession").disabled=false;$("newSession").disabled=true;$("reanalyze").disabled=true;$("sessionId").textContent="";$("setup").open=true;message("可调整配置并建立新会话。");render()}
async function restoreSession(){try{const id=$("restoreId").value.trim();const data=await api(`/api/interference/session?id=${encodeURIComponent(id)}`);restore(data);localStorage.setItem("interference-session-id",id);message("会话已恢复。")}catch(e){message(e.message)}}
function conditionsFor(exp){const spec=specs[exp-1];if(spec.scan){const raw=localStorage.getItem(`interference-scan-${session?.id||"new"}-${exp}`);const parsed=raw?raw.split(",").map(Number).filter(Number.isFinite):[];const vals=parsed.length?parsed:spec.scan.values;return vals.flatMap(value=>(spec.scan.states||[["",""]]).map(([state,label])=>({key:state?`${value}_${state}`:String(value),label:`${value} ${spec.scan.label.replace(/.* (Ω|cm|cm²|°)/,"$1")} ${label}`.trim(),variables:{[spec.scan.key]:value},state})));}return spec.conditions.map(([key,label])=>({key,label,variables:{}}));}
function savedCount(exp,key){return session?.runs.filter(r=>r.experiment===exp&&r.condition===key).length||0;}
function render(){const list=$("experimentList");list.innerHTML="";specs.forEach((s,i)=>{const b=document.createElement("button");b.className=`exp ${current===i+1?"active":""} ${session?.completed_experiments.includes(i+1)?"done":""}`;b.textContent=`${String(i+1).padStart(2,"0")} · ${s.title}`;b.onclick=()=>{if(captureId!==null)return;current=i+1;location.hash=`exp-${current}`;conditionIndex=0;latestWave=null;selectedPreview=null;render()};list.append(b)});const spec=specs[current-1],conditions=conditionsFor(current);conditionIndex=Math.min(conditionIndex,conditions.length-1);const active=conditions[conditionIndex];$("experimentNumber").textContent=`实验 ${String(current).padStart(2,"0")} / 12`;$("experimentTitle").textContent=spec.title;$("purpose").textContent=spec.purpose;$("wiring").textContent=spec.wiring;$("warning").textContent=spec.warning||"";$("progress").textContent=session?`${session.runs.filter(r=>r.experiment===current).length} 次已保存`:"请先建立会话";
  $("variables").innerHTML="";if(spec.scan){const l=document.createElement("label");l.textContent=`扫描值（逗号分隔）· ${spec.scan.label}`;const input=document.createElement("input");input.id="scanValues";input.value=localStorage.getItem(`interference-scan-${session?.id||"new"}-${current}`)||spec.scan.values.join(",");input.disabled=captureId!==null;input.onchange=()=>{if(session){localStorage.setItem(`interference-scan-${session.id}-${current}`,input.value);conditionIndex=0;render()}};l.append(input);$("variables").append(l)}for(const [key,label,type] of spec.fields||[]){const l=document.createElement("label");l.textContent=label;const input=document.createElement("input");input.id=`var_${key}`;input.type=type;if(captureId!==null&&pendingVariables?.[key]!==undefined)input.value=pendingVariables[key];l.append(input);$("variables").append(l)}
  $("conditions").innerHTML="";conditions.forEach((c,i)=>{const d=document.createElement("div");d.className=`condition ${i===conditionIndex?"active":""}`;d.textContent=`${i+1}. ${c.label}`;const small=document.createElement("small");small.textContent=`${savedCount(current,c.key)} / ${session?.repeats||3} 次已保存`;d.append(small);d.onclick=()=>{if(captureId!==null)return;conditionIndex=i;render()};$("conditions").append(d)});renderGuide(active);refreshStartEnabled();$("saveCondition").disabled=!captureReady;$("nextCondition").disabled=!session||captureId!==null||conditionIndex>=conditions.length-1||savedCount(current,active.key)<session.repeats;$("finishExperiment").disabled=!session||captureId!==null||conditions.some(c=>savedCount(current,c.key)<session.repeats);$("stopCapture").disabled=!captureId||captureReady;$("exportJson").disabled=!session;$("exportCsv").classList.toggle("disabled",!session);if(session)$("exportCsv").href=`/api/interference/export?id=${encodeURIComponent(session.id)}`;renderSummary();}
function checklistKey(){const c=conditionsFor(current)[conditionIndex];return `${session?.id||"none"}:${current}:${c.key}:${savedCount(current,c.key)}`}
function checklistReady(){const checks=checklistState.get(checklistKey());return Boolean(checks&&checks.every(Boolean))}
function refreshStartEnabled(){const c=conditionsFor(current)[conditionIndex];$("startCondition").disabled=!session||captureId!==null||savedCount(current,c.key)>=session.repeats||!checklistReady()}
function renderGuide(condition){const guide=fullGuide[current-1];if(!guide)return;$("guideAim").textContent=guide.aim;$("guideReadout").textContent=`计算与图：${guide.readout}`;$("guideInterpret").textContent=`结果解释：${guide.interpret}`;$("guideCaution").textContent=`注意：${guide.caution}`;$("manualExperiment").href=`/interference/manual#experiment-${String(current).padStart(2,"0")}`;for(const [id,items] of [["guideBefore",guide.before],["guideDuring",guide.during]]){const list=$(id);list.innerHTML="";for(const line of items){const li=document.createElement("li");li.textContent=line;list.append(li)}}const key=checklistKey(),state=checklistState.get(key)||[false,false,false,false],checks=[`已按“${condition.label}”完成对应接线，确认本次只改变指定变量。`,`改接线前已停止激励；当前通道、探头倍率和输入量程已核对。`,`已记录当前人工变量与实际接线，75 kHz、功放增益和偏置磁场保持固定。`,`已检查触发、基线/发射/尾振/回波窗口，准备采集第 ${savedCount(current,condition.key)+1} 次。`];$("guideChecklist").innerHTML="";checks.forEach((line,i)=>{const label=document.createElement("label");label.className="guideCheck";const input=document.createElement("input");input.type="checkbox";input.checked=state[i];input.onchange=()=>{const next=checklistState.get(key)||[false,false,false,false];next[i]=input.checked;checklistState.set(key,next);refreshStartEnabled()};label.append(input,document.createTextNode(line));$("guideChecklist").append(label)})}
function variableValues(){const c=conditionsFor(current)[conditionIndex],vars={...c.variables};for(const [key] of specs[current-1].fields||[]){const input=$(`var_${key}`);if(input.value)vars[key]=input.type==="number"?Number(input.value):input.value;}return vars;}
async function startCondition(){try{const c=conditionsFor(current)[conditionIndex];if(!checklistReady())throw Error("请先完成当前条件的四项操作核对");validateWindows();if(!await askConfirm(`请确认已按“${c.label}”完成物理接线，功放增益和偏置磁场未变化，然后开始采集。`))return;pendingVariables=variableValues();const response=await api("/api/capture","POST",{...session.config,simulate:$("simulate").checked});captureId=response.capture_id;captureReady=false;$("status").textContent=`采集 #${captureId}`;render();let status;for(let i=0;i<300;i++){await new Promise(resolve=>setTimeout(resolve,350));status=await api("/api/status");if(status.capture_id!==captureId)throw Error("采集已被其他任务取代");if(!["running","paused"].includes(status.state))break;}if(status?.state!=="complete")throw Error(status?.message||"采集未完成");const result=await api("/api/result/display","POST",{filter:{enabled:false},max_points:4000});latestWave={time_s:result.time_s,channels:result.channels};drawWave(latestWave);captureReady=true;$("status").textContent=`采集 #${captureId} 完成，待保存`;message("采集完成。确认波形后点击“保存当前条件”。");render()}catch(e){captureId=null;captureReady=false;pendingVariables=null;$("status").textContent="采集失败";message(e.message);render()}}
async function saveCondition(){try{if(!captureReady)throw Error("无待保存采集");const c=conditionsFor(current)[conditionIndex],variables=variableValues();if(current===10&&!variables.return_path)throw Error("请先记录实际回流路径和星点位置");if(current===3&&!variables.probe_description)throw Error("请先记录棒电压探头与接地方式");const reply=await api("/api/interference/run","POST",{session_id:session.id,capture_id:captureId,experiment:current,condition:c.key,variables,notes:$("notes").value,windows_us:validateWindows()});session.runs.push(reply.run);summary=reply.summary;captureId=null;captureReady=false;pendingVariables=null;$("status").textContent="采集已保存";message(`已保存原始波形 ${reply.run.raw_file}`);$("notes").value="";render();loadPreview(reply.run.id)}catch(e){message(e.message)}}
async function nextCondition(){conditionIndex++;render();}
async function finishExperiment(){try{const result=await api("/api/interference/complete","POST",{session_id:session.id,experiment:current});session=result.session;summary=result.summary;message(`实验 ${current} 已完成`);if(current<12){current++;location.hash=`exp-${current}`;conditionIndex=0}render()}catch(e){message(e.message)}}
async function reanalyze(){try{const w=validateWindows();if(!await askConfirm("将使用新窗口重算本会话全部已存采集，并覆盖旧指标和频谱，确认吗？"))return;const result=await api("/api/interference/reanalyze","POST",{session_id:session.id,windows_us:w});session=result.session;summary=result.summary;previewCache.clear();message("已重新分析全部记录");render()}catch(e){message(e.message)}}
async function stopCapture(){await api("/api/stop","POST",{});captureId=null;captureReady=false;pendingVariables=null;message("采集已停止");render()}
function value(x,digits=3){return Number.isFinite(x)?Number(x).toPrecision(digits):"—"}
function formatStat(stat){return stat?`${value(stat.mean)} ± ${value(stat.sd)}`:"—"}
function renderSummary(){if(!summary){$("summaryRows").innerHTML="";return}const rows=summary.rows.filter(r=>r.experiment===current);$("summaryRows").innerHTML="";for(const r of rows){const tr=document.createElement("tr");for(const content of [r.condition,r.repeats,formatStat(r.metrics.tx_peak_v),formatStat(r.metrics.tail_peak_v),formatStat(r.metrics.echo_peak_v),r.overflow?"是":"否"]){const td=document.createElement("td");td.textContent=content;tr.append(td)}$("summaryRows").append(tr)}$("fits").textContent=Object.entries(summary.fits).map(([k,v])=>`${k}: ${typeof v==="object"?Object.entries(v).map(([p,n])=>`${p}=${value(n)}`).join(", "):value(v)}`).join("；")||"当前数据不足以拟合";$("evidence").innerHTML="";for(const [key,label] of [["electric","电场 / 棒共模"],["magnetic","磁近场"],["common","公共阻抗"],["mechanical","机械响应"]]){const item=summary.evidence?.[key]||{level:"未观察到明显证据",reasons:[]},div=document.createElement("div");const title=document.createElement("strong");title.textContent=`${label} · ${item.level}`;const p=document.createElement("p");p.textContent=item.reasons.join("；")||"尚无满足判据的数据";div.append(title,p);$("evidence").append(div)}drawCompare();void updateSpectra()}
function plot(canvas,series,xlabel){const ctx=canvas.getContext("2d"),box=canvas.getBoundingClientRect(),w=canvas.width=Math.max(350,Math.round(box.width*devicePixelRatio)),h=canvas.height=Math.round(290*devicePixelRatio);ctx.fillStyle="#101113";ctx.fillRect(0,0,w,h);const points=series.flatMap(s=>s.points).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));if(!points.length){ctx.fillStyle="#a0a3a8";ctx.font=`${14*devicePixelRatio}px sans-serif`;ctx.fillText("暂无数据",20,35);return}let xmin=Math.min(...points.map(p=>p[0])),xmax=Math.max(...points.map(p=>p[0])),ymin=Math.min(0,...points.map(p=>p[1])),ymax=Math.max(...points.map(p=>p[1]));if(xmin===xmax)xmax=xmin+1;if(ymin===ymax)ymax=ymin+1;const l=50*devicePixelRatio,r=w-15*devicePixelRatio,t=20*devicePixelRatio,b=h-30*devicePixelRatio;ctx.strokeStyle="#444649";ctx.beginPath();ctx.moveTo(l,t);ctx.lineTo(l,b);ctx.lineTo(r,b);ctx.stroke();ctx.fillStyle="#a0a3a8";ctx.font=`${11*devicePixelRatio}px sans-serif`;ctx.fillText(value(ymax),3,t+10);ctx.fillText(value(ymin),3,b);ctx.fillText(value(xmin),l,b+17*devicePixelRatio);ctx.fillText(`${value(xmax)} ${xlabel}`,r-75*devicePixelRatio,b+17*devicePixelRatio);series.forEach((s,i)=>{ctx.strokeStyle=s.color||experimentAccent();ctx.lineWidth=1.5*devicePixelRatio;ctx.setLineDash(s.color?[]:[[],[6,3],[2,3],[8,3,2,3]][i%4].map(v=>v*devicePixelRatio));ctx.beginPath();s.points.forEach(([x,y],j)=>{const px=l+(x-xmin)/(xmax-xmin)*(r-l),py=b-(y-ymin)/(ymax-ymin)*(b-t);j?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=ctx.strokeStyle;ctx.fillText(s.name||"",l+5,t+(i+1)*14*devicePixelRatio)})}
function drawWave(w){if(!w)return;const series=Object.entries(w.channels).slice(0,3).map(([name,values])=>({name:`CH ${name}`,color:picoTraceColors[names.indexOf(name)],points:values.map((v,i)=>[w.time_s[i]*1e6,v])}));plot($("waveChart"),series,"μs");const canvas=$("waveChart"),ctx=canvas.getContext("2d"),xmin=w.time_s[0]*1e6,xmax=w.time_s.at(-1)*1e6,t0=n("t0"),left=50*devicePixelRatio,right=canvas.width-15*devicePixelRatio;if(t0>=xmin&&t0<=xmax){const x=left+(t0-xmin)/(xmax-xmin)*(right-left);ctx.strokeStyle="#c98435";ctx.setLineDash([5*devicePixelRatio,4*devicePixelRatio]);ctx.beginPath();ctx.moveTo(x,10*devicePixelRatio);ctx.lineTo(x,canvas.height-30*devicePixelRatio);ctx.stroke();ctx.setLineDash([])}}
function drawCompare(){const key=$("metric").value;const rows=summary?.rows.filter(r=>r.experiment===current)||[];const groups={};rows.forEach((r,i)=>{const name=r.condition.includes("float")?"浮空":r.condition.includes("grounded")?"接棒":r.condition;const x=Number(Object.values(r.variables)[0]);(groups[name]??=[]).push([Number.isFinite(x)?x:i+1,r.metrics[key]?.mean])});plot($("compareChart"),Object.entries(groups).map(([name,points])=>({name,points:points.filter(p=>Number.isFinite(p[1])).sort((a,b)=>a[0]-b[0])})),"变量 / 条件序号");renderInterpretation()}
function renderInterpretation(){if(!summary)return;$("conclusion").textContent=summary.conclusions?.[String(current)]||"证据不足";const comparisons=(summary.comparisons||[]).filter(c=>c.experiment===current);const key=$("metric").value;plot($("ratioChart"),[{name:"抑制比 dB",points:comparisons.map((c,i)=>[c.distance_cm??i+1,c.metrics[key]?.suppression_db]).filter(p=>Number.isFinite(p[1]))}],current===4?"cm":"条件序号");$("comparisons").innerHTML="";for(const c of comparisons){const p=document.createElement("p");p.textContent=`${c.distance_cm?`距离 ${c.distance_cm} cm · `:""}${c.left} / ${c.right}：`+Object.entries(c.metrics).map(([name,v])=>`${name} ${value(v.suppression_db)} dB${v.delta!==undefined?`，差值 ${value(v.delta)}`:""}`).join("；");$("comparisons").append(p)}}
async function getPreview(runId){if(!previewCache.has(runId))previewCache.set(runId,await api(`/api/interference/preview?id=${encodeURIComponent(session.id)}&run=${encodeURIComponent(runId)}`));return previewCache.get(runId)}
async function loadPreview(runId){try{selectedPreview=await getPreview(runId);drawWave(selectedPreview);drawFft();const run=session.runs.find(r=>r.id===runId);$("runMetrics").textContent=run?`发射峰值 ${value(run.metrics.tx.peak_v)} V · 尾振峰值 ${value(run.metrics.tail.peak_v)} V · 回波峰值 ${value(run.metrics.echo?.peak_v)} V · SNR ${value(run.metrics.snr_echo_db)} dB${run.metrics.simulated?" · 仿真数据":""}${run.metrics.overflow_channels.length?" · 输入溢出，比较无效":""}`:"";}catch(e){message(e.message)}}
async function updateSpectra(){if(!session)return;const generation=++spectraGeneration,latest=new Map();for(const run of session.runs)if(run.experiment===current)latest.set(run.condition,run);const chosen=[...latest.values()].slice(0,16);const previews=await Promise.all(chosen.map(r=>getPreview(r.id).catch(()=>null)));if(generation!==spectraGeneration)return;comparisonSpectra=chosen.flatMap((r,i)=>previews[i]?[{name:r.condition,preview:previews[i]}]:[]);drawFft()}
function drawFft(){const region=$("fftRegion").value,items=comparisonSpectra.length?comparisonSpectra:selectedPreview?[{name:"当前采集",preview:selectedPreview}]:[];plot($("fftChart"),items.flatMap(item=>{const s=item.preview.spectra?.[region];return s?[{name:item.name,points:s.fft_hz.map((f,i)=>[f/1000,s.fft_amplitude_v[i]])}]:[]}),"kHz")}
$("createSession").onclick=createSession;$("newSession").onclick=newSession;$("restoreSession").onclick=restoreSession;$("startCondition").onclick=startCondition;$("saveCondition").onclick=saveCondition;$("nextCondition").onclick=nextCondition;$("finishExperiment").onclick=finishExperiment;$("reanalyze").onclick=reanalyze;$("stopCapture").onclick=stopCapture;$("metric").onchange=drawCompare;$("fftRegion").onchange=drawFft;$("exportJson").onclick=()=>{const blob=new Blob([JSON.stringify({session,summary},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`interference_${session.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("waveChart").onclick=event=>{if(!captureReady||!latestWave)return;const rect=$("waveChart").getBoundingClientRect(),fraction=((event.clientX-rect.left)*devicePixelRatio-50*devicePixelRatio)/($("waveChart").width-65*devicePixelRatio);if(fraction<0||fraction>1)return;const t0=(latestWave.time_s[0]+fraction*(latestWave.time_s.at(-1)-latestWave.time_s[0]))*1e6;$("t0").value=t0.toFixed(2);drawWave(latestWave);message(`当前采集激励起点设为 ${t0.toFixed(2)} μs；请检查分析窗口是否仍落在记录范围内。`)};
document.querySelectorAll("[data-ui-theme-choice]").forEach(button=>button.addEventListener("click",()=>applyUiTheme(button.dataset.uiThemeChoice,true)));
applyUiTheme(localStorage.getItem(UI_THEME_KEY)||"light");
initialize().catch(e=>message(e.message));


// Presentation only: experiment context, genuine data, and a persistent action strip.
(() => {
 const main=document.querySelector('section.main'),task=document.querySelector('.experiment-workspace');
 const make=(tag,cls,text='')=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};
 document.body.classList.add('experiment-workstation');
 document.querySelector('main>aside').append($('newSession'));
 const intro=make('div','experiment-intro'),heading=make('h1','','干扰实验'),detail=make('span','','PicoScope 4824A · 实验会话');intro.append(heading,detail);
 const stage=make('section','experiment-signal-stage'),bar=make('div','experiment-view-tabs'),viewport=make('div','experiment-viewport'),inspector=make('aside','experiment-inspector'),footer=make('footer','experiment-actions');
 const panels=[task,...main.querySelectorAll('.data-stage,.evidence-stage')];
 const names=['接线与条件','波形 / 频谱','条件比较','综合证据'];
 let currentView=0;
 function paint(){requestAnimationFrame(()=>{if(latestWave||selectedPreview)drawWave(latestWave||selectedPreview);drawFft();drawCompare();});}
 panels.forEach((panel,i)=>{viewport.append(panel);const b=make('button','',names[i]);b.type='button';bar.append(b);b.onclick=()=>selectView(i);});
 function selectView(index){currentView=index;panels.forEach((n,i)=>n.hidden=i!==index);[...bar.querySelectorAll('[data-view]')].forEach((n,i)=>n.setAttribute('aria-pressed',String(i===index)));paint();}
 [...bar.children].forEach((n,i)=>n.dataset.view=String(i));
 const params=make('button','experiment-parameters','会话 / 分析窗口');params.type='button';params.setAttribute('aria-expanded','false');bar.append(params);
 const title=make('div','experiment-inspector-heading'),close=make('button','','×');close.type='button';close.setAttribute('aria-label','关闭实验参数');title.append(make('strong','','实验参数'),close);inspector.append(title,$('setup'),$('windowsBox'));inspector.hidden=true;
 function toggle(open){inspector.hidden=!open;stage.classList.toggle('has-inspector',open);params.setAttribute('aria-expanded',String(open));paint();}params.onclick=()=>toggle(inspector.hidden);close.onclick=()=>toggle(false);
 footer.append(task.querySelector('.actions'),task.querySelector('#message'));stage.append(bar,viewport,inspector,footer);main.prepend(intro,stage);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!inspector.hidden){toggle(false);params.focus();}});
 $('createSession').addEventListener('click',()=>{const check=()=>{if(session){toggle(false);selectView(0);}else setTimeout(()=>{if(session){toggle(false);selectView(0);}},800);};setTimeout(check,400);});
 $('startCondition').addEventListener('click',()=>{if(checklistReady()&&session)selectView(1);});
 $('newSession').addEventListener('click',()=>setTimeout(()=>{if(!session)toggle(true);},400));
 const observer=new ResizeObserver(paint);observer.observe(viewport);selectView(0);toggle(!session);
})();
