/* Bias-scan task UI: shared Shell / Stage / Inspector; hardware lives on server. */
(() => {
  'use strict';
  const ui=WaveGuardUI.createStage({page:'bias-scan',title:'偏置响应 · PZT 评价',className:'bias-stage',inspectorTitle:'稳定与保护'});
  document.querySelector('.monitor-stack').insertBefore(ui.stage,document.querySelector('.event-panel'));
  const rail=document.createElement('section');rail.className='panel bias-controls';rail.dataset.pages='bias-scan';
  rail.innerHTML=`<div class="panel-heading"><h2>偏置电源</h2><small>IT6524D · USB</small></div>
    <label class="bias-check"><input id="biasSimulate" type="checkbox" checked>仿真闭环 · 不操作硬件</label>
    <label>USB VISA 资源<select id="biasResource"><option value="">选择资源</option></select></label>
    <div class="bias-row"><button id="biasDiscover">查找 USB</button><button id="biasConnect">连接并断电</button></div>
    <p id="biasPowerState" class="bias-note">实机限值待定 · 实机启动锁定</p><button id="biasRecoverBtn" type="button">确认断电并恢复</button>
    <label>本次扫描名称<input id="biasScanName" type="text" maxlength="64" placeholder="留空使用全局命名设置"></label><p class="bias-save-location" id="biasSaveLocation">自动保存：data/bias_scans / 扫描任务 / 每档电流 / 每次波形</p><div class="subhead"><span>扫描范围</span><small id="biasRangeLimit">默认上限 6 A</small></div>
    <div class="form-grid"><label>起始 A<input id="biasStart" type="number" value="0" min="0" max="6" step="0.5"></label><label>终止 A<input id="biasEnd" type="number" value="6" min="0" max="6" step="0.5"></label><label>步长 A<input id="biasStep" type="number" value="0.5" min="0.01" max="6" step="0.1"></label><label>每档次数<select id="biasRepeats">${[5,6,7,8,9,10].map(n=>`<option ${n===10?'selected':''}>${n}</option>`).join('')}</select></label><label>记录窗口 μs<input id="biasDuration" type="number" value="2000" min="1"></label><label>开始间隔 ms<input id="biasInterval" type="number" value="100" min="0"></label></div>
    <div class="subhead"><span>直达波评价</span><small>先滤波 · 再取时间窗</small></div>
    <label class="bias-check"><input id="biasFilterEnabled" type="checkbox" checked>带通滤波后 Vpp</label>
    <div class="form-grid"><label>带通下限 kHz<input id="biasFilterLow" type="number" value="60" min="0" step="1"></label><label>带通上限 kHz<input id="biasFilterHigh" type="number" value="90" min="0" step="1"></label><label>过渡带 kHz<input id="biasFilterTransition" type="number" value="5" min="0" step="1"></label></div>
    <label>PZT 通道<select id="biasChannel">${'ABCDEFGH'.split('').map(c=>`<option>${c}</option>`).join('')}</select></label>
    <div class="form-grid"><label>起点 μs<input id="biasWindowStart" type="number" value="100"></label><label>终点 μs<input id="biasWindowEnd" type="number" value="400"></label></div>
    <label>重复统计方式<select id="biasAggregation"><option value="trimmed_mean">去一个最高 / 最低后均值</option><option value="mean">普通均值</option><option value="median">中位数</option></select></label><p class="bias-note">每档每项指标分别统计。误差棒为参与统计样本的标准差；原始重复全部保留。</p>
    <div class="subhead"><span>激励电压 / 电流</span><small>原始信号 Vpp</small></div>
    <div class="form-grid"><label>电压通道<select id="biasExcVoltage"><option value="">不启用</option>${'ABCDEFGH'.split('').map(c=>`<option>${c}</option>`).join('')}</select></label><label>电流通道<select id="biasExcCurrent"><option value="">不启用</option>${'ABCDEFGH'.split('').map(c=>`<option>${c}</option>`).join('')}</select></label><label>电压系数 V/V<input id="biasExcVoltageScale" type="number" value="1" min="0.000001" step="any"></label><label>电流系数 A/V<input id="biasExcCurrentScale" type="number" value="1" min="0.000001" step="any"></label><label>激励起点 μs<input id="biasExcStart" type="number" value="0"></label><label>激励终点 μs<input id="biasExcEnd" type="number" value="100"></label></div><p class="bias-note">通道须在实时测量中启用。电流探头填 A/V；分流电阻填 1/R。激励使用独立时间窗，不使用 PZT 带通。</p>
    <div class="subhead"><span>实时测量设置快照</span><button id="biasSnapshot">更新</button></div><p id="biasSnapshotText" class="bias-note"></p>`;
  document.querySelector('.control-stack').append(rail);
  ui.inspector.insertAdjacentHTML('beforeend',`<section><h3>稳定判据</h3><div class="form-grid"><label>绝对误差 A<input id="biasAbs" type="number" value="0.05" step="0.01"></label><label>相对误差 %<input id="biasRel" type="number" value="1" step="0.1"></label><label>保持 ms<input id="biasHold" type="number" value="200"></label><label>查询 ms<input id="biasPoll" type="number" value="50"></label></div></section>
    <section><h3>实机安全限值</h3><p class="bias-note">必须填写并验证；留空时只允许仿真。仅软件模式无需外部适配器，但仍需这些限值。</p><div class="form-grid"><label>电压合规上限 V<input id="biasVoltage" type="number" placeholder="待确认"></label><label>最大通电 s<input id="biasMaxOn" type="number" placeholder="待确认"></label><label>稳定超时 s<input id="biasStableTimeout" type="number" placeholder="待确认"></label><label><span id="biasCooldownLabel">6 A 基准冷却 s</span><input id="biasCooldown" type="number" placeholder="待确认"></label><label>实际电流上限 A<input id="biasCurrentLimit" type="number" value="6" max="6"></label><label>内存预算 MB<input id="biasMemory" type="number" value="256"></label></div></section>
    <section><h3>冷却与温度</h3><label>模式<select id="biasCoolingMode"><option value="current">随电流变化 · I²</option><option value="current_temperature">随电流变化 + 温度恢复</option><option value="fixed">固定冷却</option><option value="temperature">固定冷却 + 温度恢复</option></select></label><label id="biasCooldownMinWrap">最短冷却 s<input id="biasCooldownMin" type="number" min="0" placeholder="待确认"></label><p id="biasCoolingHint" class="bias-note">等待 = max(最短冷却, 6 A 基准时间 × (电流 / 6 A)²)。取目标与实测峰值的较大值；0 A 不额外冷却。此策略不是温度预测，需根据线圈实际热表现设置。</p><div class="form-grid"><label>温度上限 °C<input id="biasTempLimit" type="number" placeholder="未接入"></label><label>恢复温度 °C<input id="biasTempResume" type="number" placeholder="未接入"></label><label>温度有效期 s<input id="biasTempAge" type="number" value="1"></label><label>恢复超时 s<input id="biasTempWait" type="number" value="300"></label></div></section>
    <section><h3>关断保护模式</h3><label>保护方式<select id="biasProtectionMode"><option value="software">仅软件保护 · 无需外部适配器</option><option value="independent">软件 + 独立超时断电适配器</option></select></label><div id="biasIndependentControls" hidden><label class="bias-check"><input id="biasInductive" type="checkbox">已确认续流 / 钳位保护</label><label class="bias-check"><input id="biasIndependent" type="checkbox">已验证独立超时断电机制</label><label>保护配置记录<textarea id="biasProtectionNotes" rows="3" placeholder="保护器件、超时断电接口与验证记录"></textarea></label></div><p id="biasProtectionHint" class="bias-note">仅软件模式保留超时、过流和异常关断。程序强杀、USB 断开或电脑断电后无法保证断电；输出关闭也不等于线圈储能已释放。</p></section>`);
  ui.views.insertAdjacentHTML('beforeend','<span id="biasDataBadge" class="bias-badge">SIMULATED · 待采集</span>');
  ui.content.innerHTML=`<div class="bias-readouts"><span>当前档<strong id="biasPointReadout">—</strong></span><span>重复<strong id="biasRepeatReadout">—</strong></span><span>实际电流<strong id="biasActualReadout">— A</strong></span><span>通电<strong id="biasOnReadout">— s</strong></span><span>输出确认<strong id="biasOffReadout">未连接</strong></span><span>最佳已测电流<strong id="biasBestReadout">— A</strong></span></div>
    <div class="bias-job-progress"><div><span id="biasProgressText">待开始</span><span>已运行 <b id="biasElapsed">00:00</b> · 预计剩余 <b id="biasEta">—</b></span></div><progress id="biasProgress" max="1" value="0" aria-label="扫描进度"></progress></div><div class="bias-plot"><canvas id="biasResponseCanvas" aria-label="偏置电流与 Vpp 均值及样本标准差"></canvas><div id="biasEmpty" class="bias-empty"><strong>等待偏置响应</strong><span>数据在每档断电、保存后落位。</span><small>0 A 为断电基线 · 同一采集快照贯穿扫描</small></div></div>
    <div class="bias-detail"><div class="bias-detail-toolbar"><label>已测电流<select id="biasPointSelect"><option value="">尚无记录</option></select></label><label>重复<select id="biasRepeatSelect"><option value="1">1</option></select></label><label>波形<select id="biasPreviewRole"><option value="pzt">PZT</option><option value="voltage">激励电压</option><option value="current">激励电流</option></select></label><span id="biasPreviewMeta">选择某档查看评价波形</span><button id="biasTableToggle">逐档统计</button></div><canvas id="biasWaveCanvas" aria-label="指定档 PZT 评价波形"></canvas><div id="biasSummaryTable" hidden><table><thead><tr><th>目标 A</th><th>实际 A</th><th>有效次数</th><th>PZT 统计 V</th><th>样本 SD V</th><th>参与数</th><th>激励电压 Vpp V</th><th>电压 SD V / n</th><th>激励电流 Vpp A</th><th>电流 SD A / n</th><th>冷却 s</th><th>最佳评选</th></tr></thead><tbody></tbody></table></div></div>`;
  ui.footer.innerHTML='<div class="bias-primary-actions"><button id="biasStartBtn">开始仿真扫描</button><button id="biasStopBtn" disabled>停止并断电</button></div><span id="biasTaskMessage">准备就绪 · SIMULATED</span><div class="bias-export-actions"><select id="biasExportKind" aria-label="导出内容"><option value="all.zip">全部数据 ZIP</option><option value="summary.csv">逐档 CSV</option><option value="runs.csv">逐次 CSV</option><option value="result.json">任务 JSON</option><option value="config.json">配置快照</option></select><button id="biasExportBtn" disabled>导出</button><button id="biasFolderBtn" disabled>保存目录</button></div>';
  const node=id=>document.getElementById(id), number=id=>Number(node(id).value), optional=id=>node(id).value.trim()===''?null:number(id);
  const fields=['biasAggregation','biasExcVoltage','biasExcCurrent','biasExcVoltageScale','biasExcCurrentScale','biasExcStart','biasExcEnd','biasScanName','biasStart','biasEnd','biasStep','biasRepeats','biasDuration','biasInterval','biasChannel','biasWindowStart','biasWindowEnd','biasFilterEnabled','biasFilterLow','biasFilterHigh','biasFilterTransition','biasProtectionMode','biasAbs','biasRel','biasHold','biasPoll','biasVoltage','biasMaxOn','biasStableTimeout','biasCooldown','biasCooldownMin','biasCurrentLimit','biasMemory','biasCoolingMode','biasTempLimit','biasTempResume','biasTempAge','biasTempWait','biasInductive','biasIndependent','biasProtectionNotes'];
  let snapshot=null, result=null, preview=null, lastKey='', request=0, generation=0, loading=false, pendingRefresh=false, recovering=false, starting=false, actionError='';
  const fmt=(n,d=4)=>n==null?'—':Number(n).toFixed(d).replace(/(\.\d*?[1-9])0+$|\.0+$/,'$1');
  function snapshotNow(){snapshot=JSON.parse(JSON.stringify(buildPayload()));delete snapshot.simulate;node('biasSnapshotText').textContent=`${fmt(snapshot.sample_rate_hz/1e6,3)} MS/s · ${Object.entries(snapshot.channels).filter(([,v])=>v.enabled).map(([c])=>c).join('/')} · 触发 ${snapshot.trigger.source} · AWG ${snapshot.awg.enabled?'ON':'OFF'} / ${fmt(snapshot.awg.frequency_hz/1000,2)} kHz\n启动时自动冻结当前设置，记录窗口由本页覆盖。`;}
  function payload(){return {simulate:node('biasSimulate').checked,config:snapshot,bias:{aggregation:node('biasAggregation').value,excitation_voltage_channel:node('biasExcVoltage').value,excitation_current_channel:node('biasExcCurrent').value,excitation_voltage_scale:number('biasExcVoltageScale'),excitation_current_scale:number('biasExcCurrentScale'),excitation_start_us:number('biasExcStart'),excitation_end_us:number('biasExcEnd'),scan_name:node('biasScanName').value.trim(),start_a:number('biasStart'),stop_a:number('biasEnd'),step_a:number('biasStep'),repeats:number('biasRepeats'),record_duration_us:number('biasDuration'),interval_s:number('biasInterval')/1000,pzt_channel:node('biasChannel').value,direct_start_us:number('biasWindowStart'),direct_end_us:number('biasWindowEnd'),filter_enabled:node('biasFilterEnabled').checked,filter_low_hz:number('biasFilterLow')*1000,filter_high_hz:number('biasFilterHigh')*1000,filter_transition_hz:number('biasFilterTransition')*1000,protection_mode:node('biasProtectionMode').value,stable_abs_a:number('biasAbs'),stable_rel:number('biasRel')/100,stable_hold_s:number('biasHold')/1000,poll_s:number('biasPoll')/1000,voltage_limit_v:optional('biasVoltage'),max_on_s:optional('biasMaxOn'),stable_timeout_s:optional('biasStableTimeout'),cooldown_s:optional('biasCooldown'),cooldown_min_s:optional('biasCooldownMin'),actual_current_limit_a:number('biasCurrentLimit'),memory_limit_mb:number('biasMemory'),cooling_mode:node('biasCoolingMode').value,temperature_limit_c:optional('biasTempLimit'),temperature_resume_c:optional('biasTempResume'),temperature_max_age_s:number('biasTempAge'),temperature_wait_timeout_s:number('biasTempWait'),inductive_protection_confirmed:node('biasInductive').checked,independent_cutoff_confirmed:node('biasIndependent').checked,protection_notes:node('biasProtectionNotes').value}};}
  const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
  function message(text){node('biasTaskMessage').textContent=text;}function actionFailure(text){actionError=text;message(text);}
  node('biasSnapshot').onclick=snapshotNow;
  function updateMode(){const independent=node('biasProtectionMode').value==='independent';node('biasIndependentControls').hidden=!independent;node('biasProtectionHint').textContent=independent?'需接入并验证独立超时适配器。确认框不会接入硬件；输出关闭不等于线圈储能已释放。':'仅软件模式保留超时、过流和异常关断。程序强杀、USB 断开或电脑断电后无法保证断电；输出关闭也不等于线圈储能已释放。';node('biasStartBtn').textContent=node('biasSimulate').checked?'开始仿真扫描':'预检并开始扫描';node('biasDataBadge').textContent=node('biasSimulate').checked?'SIMULATED · 待采集':independent?'实机 · 独立保护模式':'实机 · 仅软件保护';}node('biasSimulate').onchange=updateMode;node('biasProtectionMode').onchange=updateMode;function updateCooling(){const current=node('biasCoolingMode').value.startsWith('current');node('biasCooldownLabel').textContent=current?'6 A 基准冷却 s':'固定冷却 s';node('biasCooldownMinWrap').hidden=!current;node('biasCoolingHint').hidden=!current;}node('biasCoolingMode').onchange=updateCooling;
  node('biasDiscover').onclick=async()=>{try{const data=await api('/api/bias-scan/resources');node('biasResource').replaceChildren(new Option('选择资源',''),...data.resources.map(r=>new Option(r,r)));node('biasPowerState').textContent=data.resources.length?'选择资源后连接，连接时优先关闭输出。':'未发现 USB VISA 电源';}catch(e){node('biasPowerState').textContent=e.message;}};
  node('biasConnect').onclick=async()=>{try{const data=await post('/api/bias-scan/connect',{resource:node('biasResource').value});node('biasPowerState').textContent=data.identity+' · 输出已确认关闭';}catch(e){node('biasPowerState').textContent=e.message;}};
  node('biasRecoverBtn').onclick=async()=>{actionError='';recovering=true;node('biasRecoverBtn').disabled=true;message('正在确认电源关闭…');try{const data=await post('/api/bias-scan/recover',{});node('biasPowerState').textContent=data.message;message(data.message);}catch(e){node('biasPowerState').textContent=e.message;actionFailure(e.message);}finally{recovering=false;await pollStatus();}};
  node('biasStartBtn').onclick=async()=>{starting=true;actionError='';node('biasStartBtn').disabled=true;try{snapshotNow();const p=payload();await post('/api/bias-scan/preflight',p);await post('/api/bias-scan/start',p);generation++;request++;result=null;preview=null;lastKey='';node('biasPointSelect').replaceChildren(new Option('尚无记录',''));node('biasSummaryTable').querySelector('tbody').replaceChildren();paint();await pollStatus();}catch(e){actionFailure(e.message);}finally{starting=false;await pollStatus();}};
  node('biasStopBtn').onclick=async()=>{try{await post('/api/stop',{});await pollStatus();}catch(e){message(e.message);}};
  node('biasFolderBtn').onclick=()=>{if(result?.output_dir){const input=document.createElement('input');input.value=result.output_dir;WaveGuardFiles.open(input,'folder');}};
  node('biasExportBtn').onclick=()=>{location.href='/api/bias-scan/export?name='+encodeURIComponent(node('biasExportKind').value);};
  node('biasTableToggle').onclick=()=>{node('biasSummaryTable').hidden=!node('biasSummaryTable').hidden;node('biasWaveCanvas').hidden=!node('biasSummaryTable').hidden;node('biasTableToggle').setAttribute('aria-pressed',String(!node('biasSummaryTable').hidden));paint();};
  async function previewRecord(){const token=++request;if(node('biasPointSelect').value==='')return;try{const p=await api(`/api/bias-scan/preview?point=${node('biasPointSelect').value}&repeat=${node('biasRepeatSelect').value}`);if(token!==request)return;preview=p;previewCaption();paint();}catch(e){if(token===request)message(e.message);}}
  function updateRepeats(){const point=Number(node('biasPointSelect').value);node('biasRepeatSelect').replaceChildren(...(result?.runs||[]).filter(r=>r.point===point).map(r=>new Option(String(r.repeat),String(r.repeat))));previewRecord();}
  node('biasResponseCanvas').onclick=event=>{const rows=result?.summary||[];if(!rows.length)return;const r=node('biasResponseCanvas').getBoundingClientRect(),maxX=Math.max(1,...rows.map(row=>row.target_a)),value=(event.clientX-r.left-78)/Math.max(1,r.width-104)*maxX;const index=rows.reduce((best,row,i)=>Math.abs(row.target_a-value)<Math.abs(rows[best].target_a-value)?i:best,0);node('biasPointSelect').value=String(index);updateRepeats();};node('biasPointSelect').onchange=updateRepeats;node('biasRepeatSelect').onchange=previewRecord;
  async function refresh(){if(loading){pendingRefresh=true;return;}loading=true;const token=generation;try{const data=await api('/api/bias-scan/result');if(token!==generation)return;result=data;node('biasSaveLocation').textContent='已自动保存：'+data.output_dir;node('biasFolderBtn').disabled=!data.output_dir;const selection=node('biasPointSelect').value;node('biasPointSelect').replaceChildren(...data.summary.map((r,i)=>new Option(`${fmt(r.target_a,2)} A · ${r.valid_count}/${r.captured_count}`,String(i))));if([...node('biasPointSelect').options].some(o=>o.value===selection))node('biasPointSelect').value=selection;if(selection===''&&data.summary.length)updateRepeats();node('biasBestReadout').textContent=fmt(data.best_current_a,2)+' A';node('biasDataBadge').textContent=(data.simulated?'SIMULATED DATA':'MEASURED DATA')+' · '+({trimmed_mean:'去最高最低均值',mean:'普通均值',median:'中位数'}[data.configuration?.aggregation]||'普通均值');node('biasSummaryTable').querySelector('tbody').innerHTML=data.summary.map(r=>`<tr><td>${fmt(r.target_a,2)}</td><td>${fmt(r.actual_current_mean_a,3)}</td><td>${r.valid_count}/${r.captured_count}</td><td>${fmt(r.vpp_mean_v,5)}</td><td>${fmt(r.vpp_sd_v,5)}</td><td>${r.statistics_count??r.valid_count}</td><td>${fmt(r.excitation_voltage_mean_v,5)}</td><td>${fmt(r.excitation_voltage_sd_v,5)} / ${r.excitation_voltage_statistics_count??0}</td><td>${fmt(r.excitation_current_mean_a,5)}</td><td>${fmt(r.excitation_current_sd_a,5)} / ${r.excitation_current_statistics_count??0}</td><td>${fmt(r.cooldown_s,3)}</td><td>${r.eligible?'有效':'排除'}</td></tr>`).join('');paint();}catch(e){if(token===generation)message(e.message);}finally{loading=false;if(pendingRefresh){pendingRefresh=false;refresh();}}}
  window.addEventListener('waveguard-status',event=>{const status=event.detail;window.__biasTaskState=status.state;const busy=['running','paused'].includes(status.state)||status.bias_output_unknown||status.bias_cleanup_pending;node('biasStartBtn').disabled=busy||recovering||starting;node('biasStopBtn').disabled=!(status.task_kind==='bias_scan'&&['running','paused'].includes(status.state));[...rail.querySelectorAll('input,select,button'),...ui.inspector.querySelectorAll('input,select,textarea')].forEach(n=>n.disabled=["running","paused"].includes(status.state)||status.bias_cleanup_pending);node('biasRecoverBtn').disabled=recovering||['running','paused'].includes(status.state);if(status.bias_output_unknown)node('biasPowerState').textContent=status.message||'输出状态未知，请确认断电并恢复';if(status.task_kind!=='bias_scan')return;const p=status.progress||{};if(['running','paused'].includes(status.state))actionError='';message(actionError||status.message+(p.phase==='cooling'&&p.cooldown_s!=null?' · 本档 '+fmt(p.cooldown_s,2)+' s':''));node('biasPointReadout').textContent=p.target_a==null?'—':`${p.point+1}/${p.total_points} · ${fmt(p.target_a,2)} A`;node('biasRepeatReadout').textContent=p.repeat==null?'—':`${p.repeat}/${number('biasRepeats')}`;node('biasActualReadout').textContent=fmt(p.actual_current_a,3)+' A';node('biasOnReadout').textContent=fmt(p.on_elapsed_s,2)+' s';node('biasOffReadout').textContent=status.bias_output_unknown?'输出状态未知':({off:'已确认关闭',on:'输出开启',unknown:'输出状态未知'})[p.output_state]||'预检';node('biasExportBtn').disabled=['running','paused'].includes(status.state)||!status.has_bias_result;node('biasFolderBtn').disabled=['running','paused'].includes(status.state)||!status.has_bias_result;const key=status.capture_id+':'+p.completed_points+':'+status.state;if(key!==lastKey&&status.has_bias_result){lastKey=key;refresh();}});
  function setupCanvas(id){const canvas=node(id),rect=canvas.getBoundingClientRect();if(rect.width<1||rect.height<1)return null;const dpr=devicePixelRatio||1;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);return {ctx,w:rect.width,h:rect.height};}
  function axes(g,xlabel,ylabel){const {ctx:c,w,h}=g;c.strokeStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-stage-line');c.lineWidth=1;c.beginPath();c.moveTo(62,18);c.lineTo(62,h-32);c.lineTo(w-24,h-32);c.stroke();c.fillStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-data-muted');c.font='11px Consolas';c.fillText(ylabel,12,13);c.fillText(xlabel,w-115,h-9);}
  function plotResponse(){
    const g=setupCanvas('biasResponseCanvas');if(!g)return;
    const {ctx:c,w,h}=g, config=result?.configuration||{}, rows=result?.summary||[];
    const specs=[{key:'vpp_mean_v',sd:'vpp_sd_v',title:config.filter_enabled===false?'PZT 原始 Vpp / V':'PZT 滤波 Vpp / V',channel:config.pzt_channel||node('biasChannel').value}];
    if(config.excitation_voltage_channel)specs.push({key:'excitation_voltage_mean_v',sd:'excitation_voltage_sd_v',title:'激励电压 Vpp / V',channel:config.excitation_voltage_channel});
    if(config.excitation_current_channel)specs.push({key:'excitation_current_mean_a',sd:'excitation_current_sd_a',title:'激励电流 Vpp / A',channel:config.excitation_current_channel});
    node('biasEmpty').hidden=rows.some(r=>r.vpp_mean_v!=null);const maxX=Math.max(1,...rows.map(r=>r.target_a)),bottom=28,lane=(h-bottom)/specs.length;
    const x=v=>78+v/maxX*(w-104);c.font='11px Consolas, Microsoft YaHei UI';
    specs.forEach((spec,index)=>{const top=index*lane+20,base=(index+1)*lane-12,height=Math.max(10,base-top),valid=rows.filter(r=>r[spec.key]!=null),maxY=Math.max(.000001,...valid.map(r=>r[spec.key]+(r[spec.sd]||0)))*1.12,y=v=>base-v/maxY*height;
      c.strokeStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-stage-line');c.lineWidth=1;c.beginPath();c.moveTo(78,top);c.lineTo(78,base);c.lineTo(w-26,base);c.stroke();
      c.fillStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-data-muted');c.fillText(spec.title+' · CH '+spec.channel,80,index*lane+12);c.fillText(fmt(maxY,4),4,top+10);c.fillText('0',54,base+3);
      c.strokeStyle=WaveGuardUI.channelColors['ABCDEFGH'.indexOf(spec.channel)];c.fillStyle=c.strokeStyle;c.lineWidth=2;c.beginPath();let connected=false;rows.forEach(r=>{if(r[spec.key]==null){connected=false;return;}if(connected)c.lineTo(x(r.target_a),y(r[spec.key]));else c.moveTo(x(r.target_a),y(r[spec.key]));connected=true;});c.stroke();
      valid.forEach(r=>{const px=x(r.target_a),py=y(r[spec.key]),sd=r[spec.sd]||0;c.globalAlpha=r.eligible?1:.45;c.beginPath();c.moveTo(px,y(r[spec.key]+sd));c.lineTo(px,y(Math.max(0,r[spec.key]-sd)));[y(r[spec.key]+sd),y(Math.max(0,r[spec.key]-sd))].forEach(yy=>{c.moveTo(px-3,yy);c.lineTo(px+3,yy);});c.stroke();c.beginPath();c.arc(px,py,3,0,Math.PI*2);c.fill();});c.globalAlpha=1;
    });c.fillStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-data-muted');for(let i=0;i<=4;i++)c.fillText(fmt(maxX*i/4,2),x(maxX*i/4)-5,h-12);c.fillText('偏置电流 / A',w-115,h-1);
  }
  function plotWave(){const g=setupCanvas('biasWaveCanvas');if(!g)return;const role=node('biasPreviewRole').value,extra=preview?.excitation?.[role];axes(g,'Time / μs',role==='current'?'Current / A':'Voltage / V');if(!preview||(role!=='pzt'&&!extra))return;const {ctx:c,w,h}=g,t=preview.time_us,v=role==='pzt'?preview.volts:extra.values,a=t[0],b=t.at(-1),amp=Math.max(.000001,...v.map(Math.abs))*1.15;const x=u=>62+(u-a)/(b-a)*(w-86),y=u=>(h-14)/2-u/amp*(h-55)/2;c.fillStyle='rgba(201,132,53,.12)';const start=role==='pzt'?(result?.configuration?.direct_start_us??number('biasWindowStart')):result.configuration.excitation_start_us,end=role==='pzt'?(result?.configuration?.direct_end_us??number('biasWindowEnd')):result.configuration.excitation_end_us;c.fillRect(x(start),18,x(end)-x(start),h-50);c.strokeStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-stage-line');c.lineWidth=1;c.setLineDash([3,4]);c.beginPath();c.moveTo(62,y(0));c.lineTo(w-24,y(0));c.stroke();c.setLineDash([]);c.strokeStyle=WaveGuardUI.channelColors['ABCDEFGH'.indexOf(role==='pzt'?preview.channel:extra.channel)];c.lineWidth=1.5;c.beginPath();v.forEach((value,i)=>i?c.lineTo(x(t[i]),y(value)):c.moveTo(x(t[i]),y(value)));c.stroke();c.fillStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-data-muted');c.fillText('0',7,y(0)+4);c.fillText(fmt(amp,4),7,28);c.fillText(fmt(-amp,4),7,h-35);c.fillText(fmt(a,1),62,h-16);c.fillText(fmt(b,1),w-70,h-16);}
  function previewCaption(){const role=node('biasPreviewRole').value,extra=preview?.excitation?.[role];if(!preview)return;if(role!=='pzt'&&!extra){node('biasPreviewMeta').textContent='此任务未配置该激励通道';return;}node('biasPreviewMeta').textContent=role==='pzt'?`CH ${preview.channel} · 偏置 ${fmt(preview.row.actual_current_a,3)} A · ${preview.vpp_basis==='filtered'?'滤波后':'原始'} Vpp ${fmt(preview.row.vpp_v,5)} V${preview.row.valid?'':' · '+preview.row.invalid_reason}`:`CH ${extra.channel} · 偏置 ${fmt(preview.row.actual_current_a,3)} A · 激励${role==='voltage'?'电压':'电流'} · 原始 Vpp ${fmt(preview.row['excitation_'+role+'_vpp_'+(role==='voltage'?'v':'a')],5)} ${extra.unit}`;}
  node('biasPreviewRole').onchange=()=>{previewCaption();paint();};
  let timingStatus=null,timingAt=0;
  const clock=seconds=>{seconds=Math.max(0,Math.round(seconds));return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');};
  function updateTiming(){const s=timingStatus;if(!s||s.task_kind!=='bias_scan')return;const p=s.progress||{},active=['running','paused'].includes(s.state),elapsed=s.started_at?((active?Date.now()/1000:(s.finished_at||Date.now()/1000))-s.started_at):0;node('biasElapsed').textContent=clock(elapsed);const fraction=Math.max(0,Math.min(1,p.progress_fraction||0));node('biasProgress').value=fraction;node('biasProgressText').textContent=Math.round(fraction*100)+'% · '+(p.captured_count||0)+' / '+(p.total_captures||0)+' 次采集';node('biasEta').textContent=s.state==='complete'?'00:00':!active?'已中止':p.estimated_remaining_s==null?'估算中':clock(Math.max(0,p.estimated_remaining_s-(performance.now()-timingAt)/1000))+(p.eta_temperature_wait?' + 温度等待':'（估算）');}
  window.addEventListener('waveguard-status',event=>{timingStatus=event.detail;timingAt=performance.now();updateTiming();});setInterval(()=>{if(document.body.dataset.page==='bias-scan')updateTiming();},250);
  function paint(){if(document.body.dataset.page!=='bias-scan')return;plotResponse();plotWave();}
  WaveGuardUI.observe(ui.content,paint,'bias-scan');WaveGuardUI.registerPainter('bias-scan',paint);
  window.addEventListener('signal-layout',()=>{if(document.body.dataset.page==='bias-scan'){if(!['running','paused'].includes(window.__biasTaskState))snapshotNow();WaveGuardUI.requestPaint();}});
  fields.forEach(id=>node(id).addEventListener('change',()=>{try{localStorage.setItem('waveguard-bias-settings',JSON.stringify(Object.fromEntries(fields.map(key=>[key,node(key).type==='checkbox'?node(key).checked:node(key).value]))));}catch{}}));
  try{const saved=JSON.parse(localStorage.getItem('waveguard-bias-settings')||'{}');fields.forEach(id=>{if(saved[id]!=null&& !['biasInductive','biasIndependent'].includes(id)){if(node(id).type==='checkbox')node(id).checked=saved[id];else node(id).value=saved[id];}});}catch{}
  api('/api/bias-scan/limits').then(data=>{const maximum=Number(data.max_current_a);if(!Number.isFinite(maximum)||maximum<=0)return;['biasStart','biasEnd','biasStep','biasCurrentLimit'].forEach(id=>node(id).max=String(maximum));node('biasRangeLimit').textContent='允许上限 '+maximum+' A · 默认 6 A';}).catch(()=>{node('biasRangeLimit').textContent='范围读取失败 · 暂按 6 A';});
  updateCooling();updateMode();snapshotNow();WaveGuardUI.activate(document.body.dataset.page);paint();
})();
