/* Bias-scan task UI: shared Shell / Stage / Inspector; hardware lives on server. */
(() => {
  'use strict';
  const ui=WaveGuardUI.createStage({page:'bias-scan',title:'偏置响应 · 原始 PZT Vpp',className:'bias-stage',inspectorTitle:'稳定与保护'});
  document.querySelector('.monitor-stack').insertBefore(ui.stage,document.querySelector('.event-panel'));
  const rail=document.createElement('section');rail.className='panel bias-controls';rail.dataset.pages='bias-scan';
  rail.innerHTML=`<div class="panel-heading"><h2>偏置电源</h2><small>IT6524D · USB</small></div>
    <label class="bias-check"><input id="biasSimulate" type="checkbox" checked>仿真闭环 · 不操作硬件</label>
    <label>USB VISA 资源<select id="biasResource"><option value="">选择资源</option></select></label>
    <div class="bias-row"><button id="biasDiscover">查找 USB</button><button id="biasConnect">连接并断电</button></div>
    <p id="biasPowerState" class="bias-note">实机限值待定 · 实机启动锁定</p>
    <div class="subhead"><span>扫描范围</span><small>首轮上限 6 A</small></div>
    <div class="form-grid"><label>起始 A<input id="biasStart" type="number" value="0" min="0" max="6" step="0.5"></label><label>终止 A<input id="biasEnd" type="number" value="6" min="0" max="6" step="0.5"></label><label>步长 A<input id="biasStep" type="number" value="0.5" min="0.01" max="6" step="0.1"></label><label>每档次数<select id="biasRepeats">${[5,6,7,8,9,10].map(n=>`<option ${n===10?'selected':''}>${n}</option>`).join('')}</select></label><label>记录窗口 μs<input id="biasDuration" type="number" value="2000" min="1"></label><label>开始间隔 ms<input id="biasInterval" type="number" value="100" min="0"></label></div>
    <div class="subhead"><span>直达波评价</span><small>原始 · 不带通</small></div>
    <label>PZT 通道<select id="biasChannel">${'ABCDEFGH'.split('').map(c=>`<option>${c}</option>`).join('')}</select></label>
    <div class="form-grid"><label>起点 μs<input id="biasWindowStart" type="number" value="100"></label><label>终点 μs<input id="biasWindowEnd" type="number" value="400"></label></div>
    <div class="subhead"><span>实时测量设置快照</span><button id="biasSnapshot">更新</button></div><p id="biasSnapshotText" class="bias-note"></p>`;
  document.querySelector('.control-stack').append(rail);
  ui.inspector.insertAdjacentHTML('beforeend',`<section><h3>稳定判据</h3><div class="form-grid"><label>绝对误差 A<input id="biasAbs" type="number" value="0.05" step="0.01"></label><label>相对误差 %<input id="biasRel" type="number" value="1" step="0.1"></label><label>保持 ms<input id="biasHold" type="number" value="200"></label><label>查询 ms<input id="biasPoll" type="number" value="50"></label></div></section>
    <section><h3>实机安全限值</h3><p class="bias-note">必须填写并验证；留空时只允许仿真。软件关断不能替代独立硬件保护。</p><div class="form-grid"><label>电压合规上限 V<input id="biasVoltage" type="number" placeholder="待确认"></label><label>最大通电 s<input id="biasMaxOn" type="number" placeholder="待确认"></label><label>稳定超时 s<input id="biasStableTimeout" type="number" placeholder="待确认"></label><label>固定冷却 s<input id="biasCooldown" type="number" placeholder="待确认"></label><label>实际电流上限 A<input id="biasCurrentLimit" type="number" value="6" max="6"></label><label>内存预算 MB<input id="biasMemory" type="number" value="256"></label></div></section>
    <section><h3>冷却与温度</h3><label>模式<select id="biasCoolingMode"><option value="fixed">固定冷却</option><option value="temperature">固定冷却 + 温度恢复</option></select></label><div class="form-grid"><label>温度上限 °C<input id="biasTempLimit" type="number" placeholder="未接入"></label><label>恢复温度 °C<input id="biasTempResume" type="number" placeholder="未接入"></label><label>温度有效期 s<input id="biasTempAge" type="number" value="1"></label><label>恢复超时 s<input id="biasTempWait" type="number" value="300"></label></div></section>
    <section><h3>感性负载关断保护</h3><label class="bias-check"><input id="biasInductive" type="checkbox">已确认续流 / 钳位保护</label><label class="bias-check"><input id="biasIndependent" type="checkbox">已验证独立超时断电机制</label><label>保护配置记录<textarea id="biasProtectionNotes" rows="3" placeholder="保护器件、超时断电接口与验证记录"></textarea></label><p class="bias-note">确认框不会接入或武装硬件。当前独立保护适配器未接入，实机扫描仍锁定。输出关闭 ≠ 线圈储能已释放。</p></section>`);
  ui.views.insertAdjacentHTML('beforeend','<span id="biasDataBadge" class="bias-badge">SIMULATED · 待采集</span>');
  ui.content.innerHTML=`<div class="bias-readouts"><span>当前档<strong id="biasPointReadout">—</strong></span><span>重复<strong id="biasRepeatReadout">—</strong></span><span>实际电流<strong id="biasActualReadout">— A</strong></span><span>通电<strong id="biasOnReadout">— s</strong></span><span>输出确认<strong id="biasOffReadout">未连接</strong></span><span>最佳已测电流<strong id="biasBestReadout">— A</strong></span></div>
    <div class="bias-plot"><canvas id="biasResponseCanvas" aria-label="偏置电流与 Vpp 均值及样本标准差"></canvas><div id="biasEmpty" class="bias-empty"><strong>等待偏置响应</strong><span>数据在每档断电、保存后落位。</span><small>0 A 为断电基线 · 同一采集快照贯穿扫描</small></div></div>
    <div class="bias-detail"><div class="bias-detail-toolbar"><label>已测电流<select id="biasPointSelect"><option value="">尚无记录</option></select></label><label>重复<select id="biasRepeatSelect"><option value="1">1</option></select></label><span id="biasPreviewMeta">选择某档查看原始波形</span><button id="biasTableToggle">逐档统计</button></div><canvas id="biasWaveCanvas" aria-label="指定档原始 PZT 波形"></canvas><div id="biasSummaryTable" hidden><table><thead><tr><th>目标 A</th><th>实际 A</th><th>有效次数</th><th>Vpp 均值 V</th><th>样本 SD V</th><th>最佳评选</th></tr></thead><tbody></tbody></table></div></div>`;
  ui.footer.innerHTML='<button id="biasStartBtn" class="sweep-start">开始仿真扫描</button><button id="biasStopBtn" disabled>停止并断电</button><span id="biasTaskMessage">准备就绪 · SIMULATED</span><select id="biasExportKind" aria-label="导出格式"><option value="summary.csv">逐档 CSV</option><option value="runs.csv">逐次 CSV</option><option value="result.json">任务 JSON</option><option value="config.json">配置快照</option></select><button id="biasExportBtn" disabled>导出</button>';
  const node=id=>document.getElementById(id), number=id=>Number(node(id).value), optional=id=>node(id).value.trim()===''?null:number(id);
  const fields=['biasStart','biasEnd','biasStep','biasRepeats','biasDuration','biasInterval','biasChannel','biasWindowStart','biasWindowEnd','biasAbs','biasRel','biasHold','biasPoll','biasVoltage','biasMaxOn','biasStableTimeout','biasCooldown','biasCurrentLimit','biasMemory','biasCoolingMode','biasTempLimit','biasTempResume','biasTempAge','biasTempWait','biasInductive','biasIndependent','biasProtectionNotes'];
  let snapshot=null, result=null, preview=null, lastKey='', request=0, generation=0, loading=false, pendingRefresh=false;
  const fmt=(n,d=4)=>n==null?'—':Number(n).toFixed(d).replace(/(\.\d*?[1-9])0+$|\.0+$/,'$1');
  function snapshotNow(){snapshot=JSON.parse(JSON.stringify(buildPayload()));delete snapshot.simulate;node('biasSnapshotText').textContent=`${fmt(snapshot.sample_rate_hz/1e6,3)} MS/s · ${Object.entries(snapshot.channels).filter(([,v])=>v.enabled).map(([c])=>c).join('/')} · 触发 ${snapshot.trigger.source} · AWG ${snapshot.awg.enabled?'ON':'OFF'} / ${fmt(snapshot.awg.frequency_hz/1000,2)} kHz\n启动时自动冻结当前设置，记录窗口由本页覆盖。`;}
  function payload(){return {simulate:node('biasSimulate').checked,config:snapshot,bias:{start_a:number('biasStart'),stop_a:number('biasEnd'),step_a:number('biasStep'),repeats:number('biasRepeats'),record_duration_us:number('biasDuration'),interval_s:number('biasInterval')/1000,pzt_channel:node('biasChannel').value,direct_start_us:number('biasWindowStart'),direct_end_us:number('biasWindowEnd'),stable_abs_a:number('biasAbs'),stable_rel:number('biasRel')/100,stable_hold_s:number('biasHold')/1000,poll_s:number('biasPoll')/1000,voltage_limit_v:optional('biasVoltage'),max_on_s:optional('biasMaxOn'),stable_timeout_s:optional('biasStableTimeout'),cooldown_s:optional('biasCooldown'),actual_current_limit_a:number('biasCurrentLimit'),memory_limit_mb:number('biasMemory'),cooling_mode:node('biasCoolingMode').value,temperature_limit_c:optional('biasTempLimit'),temperature_resume_c:optional('biasTempResume'),temperature_max_age_s:number('biasTempAge'),temperature_wait_timeout_s:number('biasTempWait'),inductive_protection_confirmed:node('biasInductive').checked,independent_cutoff_confirmed:node('biasIndependent').checked,protection_notes:node('biasProtectionNotes').value}};}
  const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
  function message(text){node('biasTaskMessage').textContent=text;}
  node('biasSnapshot').onclick=snapshotNow;
  node('biasSimulate').onchange=()=>{node('biasStartBtn').textContent=node('biasSimulate').checked?'开始仿真扫描':'安全预检并启动';node('biasDataBadge').textContent=node('biasSimulate').checked?'SIMULATED · 待采集':'实机预检 · 保护待确认';};
  node('biasDiscover').onclick=async()=>{try{const data=await api('/api/bias-scan/resources');node('biasResource').replaceChildren(new Option('选择资源',''),...data.resources.map(r=>new Option(r,r)));node('biasPowerState').textContent=data.resources.length?'选择资源后连接，连接时优先关闭输出。':'未发现 USB VISA 电源';}catch(e){node('biasPowerState').textContent=e.message;}};
  node('biasConnect').onclick=async()=>{try{const data=await post('/api/bias-scan/connect',{resource:node('biasResource').value});node('biasPowerState').textContent=data.identity+' · 输出已确认关闭';}catch(e){node('biasPowerState').textContent=e.message;}};
  node('biasStartBtn').onclick=async()=>{node('biasStartBtn').disabled=true;try{snapshotNow();const p=payload();await post('/api/bias-scan/preflight',p);await post('/api/bias-scan/start',p);generation++;request++;result=null;preview=null;lastKey='';node('biasPointSelect').replaceChildren(new Option('尚无记录',''));node('biasSummaryTable').querySelector('tbody').replaceChildren();paint();await pollStatus();}catch(e){message(e.message);node('biasStartBtn').disabled=false;}};
  node('biasStopBtn').onclick=async()=>{try{await post('/api/stop',{});await pollStatus();}catch(e){message(e.message);}};
  node('biasExportBtn').onclick=()=>{location.href='/api/bias-scan/export?name='+encodeURIComponent(node('biasExportKind').value);};
  node('biasTableToggle').onclick=()=>{node('biasSummaryTable').hidden=!node('biasSummaryTable').hidden;node('biasWaveCanvas').hidden=!node('biasSummaryTable').hidden;node('biasTableToggle').setAttribute('aria-pressed',String(!node('biasSummaryTable').hidden));paint();};
  async function previewRecord(){const token=++request;if(node('biasPointSelect').value==='')return;try{const p=await api(`/api/bias-scan/preview?point=${node('biasPointSelect').value}&repeat=${node('biasRepeatSelect').value}`);if(token!==request)return;preview=p;node('biasPreviewMeta').textContent=`CH ${p.channel} · ${fmt(p.row.actual_current_a,3)} A · Vpp ${fmt(p.row.vpp_v,5)} V${p.row.valid?'':' · '+p.row.invalid_reason}`;paint();}catch(e){if(token===request)message(e.message);}}
  function updateRepeats(){const point=Number(node('biasPointSelect').value);node('biasRepeatSelect').replaceChildren(...(result?.runs||[]).filter(r=>r.point===point).map(r=>new Option(String(r.repeat),String(r.repeat))));previewRecord();}
  node('biasResponseCanvas').onclick=event=>{const rows=result?.summary||[];if(!rows.length)return;const r=node('biasResponseCanvas').getBoundingClientRect(),maxX=Math.max(1,...rows.map(row=>row.target_a)),value=(event.clientX-r.left-62)/Math.max(1,r.width-86)*maxX;const index=rows.reduce((best,row,i)=>Math.abs(row.target_a-value)<Math.abs(rows[best].target_a-value)?i:best,0);node('biasPointSelect').value=String(index);updateRepeats();};node('biasPointSelect').onchange=updateRepeats;node('biasRepeatSelect').onchange=previewRecord;
  async function refresh(){if(loading){pendingRefresh=true;return;}loading=true;const token=generation;try{const data=await api('/api/bias-scan/result');if(token!==generation)return;result=data;const selection=node('biasPointSelect').value;node('biasPointSelect').replaceChildren(...data.summary.map((r,i)=>new Option(`${fmt(r.target_a,2)} A · ${r.valid_count}/${r.captured_count}`,String(i))));if([...node('biasPointSelect').options].some(o=>o.value===selection))node('biasPointSelect').value=selection;if(selection===''&&data.summary.length)updateRepeats();node('biasBestReadout').textContent=fmt(data.best_current_a,2)+' A';node('biasDataBadge').textContent=data.simulated?'SIMULATED DATA':'MEASURED DATA';node('biasSummaryTable').querySelector('tbody').innerHTML=data.summary.map(r=>`<tr><td>${fmt(r.target_a,2)}</td><td>${fmt(r.actual_current_mean_a,3)}</td><td>${r.valid_count}/${r.captured_count}</td><td>${fmt(r.vpp_mean_v,5)}</td><td>${fmt(r.vpp_sd_v,5)}</td><td>${r.eligible?'有效':'排除'}</td></tr>`).join('');paint();}catch(e){if(token===generation)message(e.message);}finally{loading=false;if(pendingRefresh){pendingRefresh=false;refresh();}}}
  window.addEventListener('waveguard-status',event=>{const status=event.detail;window.__biasTaskState=status.state;const busy=['running','paused'].includes(status.state)||status.bias_output_unknown||status.bias_cleanup_pending;node('biasStartBtn').disabled=busy;node('biasStopBtn').disabled=!(status.task_kind==='bias_scan'&&['running','paused'].includes(status.state));[...rail.querySelectorAll('input,select,button'),...ui.inspector.querySelectorAll('input,select,textarea')].forEach(n=>n.disabled=["running","paused"].includes(status.state)||status.bias_cleanup_pending);if(status.task_kind!=='bias_scan')return;const p=status.progress||{};message(status.message);node('biasPointReadout').textContent=p.target_a==null?'—':`${p.point+1}/${p.total_points} · ${fmt(p.target_a,2)} A`;node('biasRepeatReadout').textContent=p.repeat==null?'—':`${p.repeat}/${number('biasRepeats')}`;node('biasActualReadout').textContent=fmt(p.actual_current_a,3)+' A';node('biasOnReadout').textContent=fmt(p.on_elapsed_s,2)+' s';node('biasOffReadout').textContent=status.bias_output_unknown?'输出状态未知':({off:'已确认关闭',on:'输出开启',unknown:'输出状态未知'})[p.output_state]||'预检';node('biasExportBtn').disabled=['running','paused'].includes(status.state)||!status.has_bias_result;const key=status.capture_id+':'+p.completed_points+':'+status.state;if(key!==lastKey&&status.has_bias_result){lastKey=key;refresh();}});
  function setupCanvas(id){const canvas=node(id),rect=canvas.getBoundingClientRect();if(rect.width<1||rect.height<1)return null;const dpr=devicePixelRatio||1;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);return {ctx,w:rect.width,h:rect.height};}
  function axes(g,xlabel,ylabel){const {ctx:c,w,h}=g;c.strokeStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-stage-line');c.lineWidth=1;c.beginPath();c.moveTo(62,18);c.lineTo(62,h-32);c.lineTo(w-24,h-32);c.stroke();c.fillStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-data-muted');c.font='11px Consolas';c.fillText(ylabel,12,13);c.fillText(xlabel,w-115,h-9);}
  function plotResponse(){const g=setupCanvas('biasResponseCanvas');if(!g)return;axes(g,'Bias current / A','PZT Vpp / V');const rows=(result?.summary||[]).filter(r=>r.vpp_mean_v!=null);node('biasEmpty').hidden=rows.length>0;if(!rows.length)return;const {ctx:c,w,h}=g,maxX=Math.max(1,...rows.map(r=>r.target_a)),maxY=Math.max(.000001,...rows.map(r=>r.vpp_mean_v+(r.vpp_sd_v||0)))*1.18;const x=v=>62+v/maxX*(w-86),y=v=>h-32-v/maxY*(h-58);c.strokeStyle=WaveGuardUI.state.accent;c.fillStyle=c.strokeStyle;c.lineWidth=2;c.beginPath();rows.forEach((r,i)=>i?c.lineTo(x(r.target_a),y(r.vpp_mean_v)):c.moveTo(x(r.target_a),y(r.vpp_mean_v)));c.stroke();rows.forEach(r=>{const px=x(r.target_a),py=y(r.vpp_mean_v),sd=r.vpp_sd_v||0;c.globalAlpha=r.eligible?1:.45;c.beginPath();c.moveTo(px,y(r.vpp_mean_v+sd));c.lineTo(px,y(Math.max(0,r.vpp_mean_v-sd)));for(const yy of [y(r.vpp_mean_v+sd),y(Math.max(0,r.vpp_mean_v-sd))]){c.moveTo(px-4,yy);c.lineTo(px+4,yy);}c.stroke();c.beginPath();c.arc(px,py,3,0,Math.PI*2);c.fill();});c.globalAlpha=1;c.fillStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-data-muted');for(let i=0;i<=4;i++){const xv=maxX*i/4,yv=maxY*i/4;c.fillText(fmt(xv,2),x(xv)-5,h-16);c.fillText(fmt(yv,5),8,y(yv)+4);}}
  function plotWave(){const g=setupCanvas('biasWaveCanvas');if(!g)return;axes(g,'Time / μs','Voltage / V');if(!preview)return;const {ctx:c,w,h}=g,t=preview.time_us,v=preview.volts,a=t[0],b=t.at(-1),amp=Math.max(.000001,...v.map(Math.abs))*1.15;const x=u=>62+(u-a)/(b-a)*(w-86),y=u=>(h-14)/2-u/amp*(h-55)/2;c.fillStyle='rgba(201,132,53,.12)';const start=result?.configuration?.direct_start_us??number('biasWindowStart'),end=result?.configuration?.direct_end_us??number('biasWindowEnd');c.fillRect(x(start),18,x(end)-x(start),h-50);c.strokeStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-stage-line');c.lineWidth=1;c.setLineDash([3,4]);c.beginPath();c.moveTo(62,y(0));c.lineTo(w-24,y(0));c.stroke();c.setLineDash([]);c.strokeStyle=WaveGuardUI.channelColors['ABCDEFGH'.indexOf(preview.channel)];c.lineWidth=1.5;c.beginPath();v.forEach((value,i)=>i?c.lineTo(x(t[i]),y(value)):c.moveTo(x(t[i]),y(value)));c.stroke();c.fillStyle=getComputedStyle(ui.stage).getPropertyValue('--wg-data-muted');c.fillText('0',7,y(0)+4);c.fillText(fmt(amp,4),7,28);c.fillText(fmt(-amp,4),7,h-35);c.fillText(fmt(a,1),62,h-16);c.fillText(fmt(b,1),w-70,h-16);}
  function paint(){if(document.body.dataset.page!=='bias-scan')return;plotResponse();plotWave();}
  WaveGuardUI.observe(ui.content,paint,'bias-scan');WaveGuardUI.registerPainter('bias-scan',paint);
  window.addEventListener('signal-layout',()=>{if(document.body.dataset.page==='bias-scan'){if(!['running','paused'].includes(window.__biasTaskState))snapshotNow();WaveGuardUI.requestPaint();}});
  fields.forEach(id=>node(id).addEventListener('change',()=>{try{localStorage.setItem('waveguard-bias-settings',JSON.stringify(Object.fromEntries(fields.map(key=>[key,node(key).type==='checkbox'?node(key).checked:node(key).value]))));}catch{}}));
  try{const saved=JSON.parse(localStorage.getItem('waveguard-bias-settings')||'{}');fields.forEach(id=>{if(saved[id]!=null&& !['biasInductive','biasIndependent'].includes(id)){if(node(id).type==='checkbox')node(id).checked=saved[id];else node(id).value=saved[id];}});}catch{}
  snapshotNow();WaveGuardUI.activate(document.body.dataset.page);paint();
})();
